name: Sync Fork with ente-io/ente

on:
  schedule:
    - cron: '0 3 * * *'  # Führt den Workflow täglich um 3:00 UTC aus
  workflow_dispatch:      # Ermöglicht manuelles Starten über den "Actions"-Tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # SCHRITT 1: Lade den Code deines Forks auf den Runner
      - name: Checkout local fork
        uses: actions/checkout@v4
        with:
          # Stellt sicher, dass der 'main'-Branch ausgecheckt wird
          ref: main
          # Holt die gesamte Git-Historie, was für den Sync wichtig ist
          fetch-depth: 0

      # SCHRITT 2: Führe die Synchronisierung mit dem Upstream-Repo durch
      - name: Sync fork with upstream repository
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main 
          upstream_sync_repo: https://github.com/ente-io/ente.git
          upstream_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
