name: Sync Fork with ente-io/ente

on:
  schedule:
    - cron: '0 3 * * *'  
  workflow_dispatch:      

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # SCHRITT 1: Lade den Code deines Forks auf den Runner
      - name: Checkout local fork
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # SCHRITT 2: Führe die Synchronisierung durch
      - name: Sync fork with upstream repository
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main 
          
          # KORREKTUR HIER: Gib nur "BENUTZER/REPO" an
          upstream_sync_repo: ente-io/ente
          
          upstream_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
